# Markdownlint configuration (keep it simple for class labs)
MD013: false   # line length
MD041: false   # first line in file should be a top-level heading (we already have one)
MD033: false   # allow inline HTML (we barely use it)
MD024: false   # allow duplicate headings in different sections
